#!/usr/bin/env bash

# If no argument is given, show usage
if [ $# -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Get IP address from argument
IP_ADDRESS=$1

# Ping the IP address 5 times
ping -c 5 $IP_ADDRESS
